// Import Google Font
import { Inter } from "next/font/google";

// Global CSS
import "./globals.css";

// Theme provider for dark/light mode
import { ThemeProvider } from "@/components/ui/theme-provider";

// Header component
import Header from "@/components/header";

// Authentication provider (Clerk)
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";


// Toast notifications
import { Toaster } from "sonner";

// Next.js Link component
import Link from "next/link";

// Initialize Inter font
const inter = Inter({ subsets: ["latin"] });

// Metadata for the entire application
export const metadata = {
  title: "Senseai - AI Career Coach",
  description: "Generated by create next app",
};

// Root layout component (wraps entire app)
export default function RootLayout({ children }) {
  return (
    // ClerkProvider wraps the whole app for authentication
    <ClerkProvider appearance={{ baseTheme: dark }}>
      
      {/* HTML root */}
      <html lang="en" suppressHydrationWarning>
        
        {/* Body with global font applied */}
        <body className={`${inter.className}`}>
          
          {/* ThemeProvider handles dark/light theme */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >

            {/* Header section (Navbar) */}
            <Header />

            {/* Main content area where page content renders */}
            <main className="min-h-screen">
              {children}
            </main>

            {/* Toast notifications */}
            <Toaster richColors />

            {/* ================= FOOTER ================= */}
            <footer className="bg-gradient-to-b from-black to-[#111827] py-12 mt-16 border-t border-white/10">
              <div className="container mx-auto px-4">
                <div className="flex flex-col items-center space-y-6 text-center">

                  {/* Brand Name */}
                  <h3 className="text-xl font-semibold text-white">
                    SENSAI
                  </h3>

                  {/* Footer description */}
                  <p className="text-gray-300 max-w-md">
                    Empowering your career with AI-driven insights,
                    interview practice, and smart guidance.
                  </p>

                  {/* Divider line */}
                  <div className="h-px w-40 bg-white/10"></div>

                  {/* Footer navigation links */}
                  <div className="flex gap-6 text-sm text-gray-400">
                    <Link href="/privacy" className="hover:text-white transition">
                      Privacy Policy
                    </Link>

                    <Link href="/terms" className="hover:text-white transition">
                      Terms of Service
                    </Link>

                    <Link href="/contact" className="hover:text-white transition">
                      Contact
                    </Link>
                  </div>

                  {/* Copyright */}
                  <p className="text-xs text-gray-500">
                    © {new Date().getFullYear()} Sensai. All rights reserved.
                  </p>

                </div>
              </div>
            </footer>

          </ThemeProvider>
        </body>
      </html>

    </ClerkProvider>
  );
}